services:
  jenkins:
    build: .
    env_file:
      - .env
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/my_marvin.yml
    ports:
      - 5000:8080
    volumes:
      - ./my_marvin.yml:/var/jenkins_home/casc_configs/my_marvin.yml