jenkins:
  systemMessage: "Welcome to the Petit-Pain-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      users:
       - id: jigglypuff
         password: admin
jobs:
  - file: /var/jenkins_home/job_dsl.groovy